import {
  IconAlertTriangle,
  IconArchive,
  IconArrowRight,
  IconArrowUpRight,
  IconBell,
  IconBold,
  IconBolt,
  IconCalendar,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleX,
  IconClock,
  IconCopy,
  IconDeviceFloppy,
  IconDots,
  IconDownload,
  IconEye,
  IconEyeOff,
  IconFileText,
  IconFilter,
  IconFolder,
  IconGripVertical,
  IconHash,
  IconHistory,
  IconInbox,
  IconItalic,
  IconLayoutDashboard,
  IconLink,
  IconList,
  IconListNumbers,
  IconLogout,
  IconMessage,
  IconMessageCircle,
  IconPencil,
  IconPhoto,
  IconPlus,
  IconQuote,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSettings,
  IconSparkles,
  IconStack2,
  IconTarget,
  IconTrash,
  IconTrendingUp,
  IconUnderline,
  IconUsers,
  IconWorld,
  IconX,
  type Icon as TablerIcon,
} from "@tabler/icons-react";

// Semantic name → Tabler icon, matching the design handoff's icons.jsx keys.
export const Icon = {
  dashboard: IconLayoutDashboard,
  pencil: IconPencil,
  calendar: IconCalendar,
  archive: IconArchive,
  chart: IconChartBar,
  settings: IconSettings,
  plus: IconPlus,
  check: IconCheck,
  checkCircle: IconCircleCheck,
  x: IconX,
  xCircle: IconCircleX,
  clock: IconClock,
  send: IconSend,
  eye: IconEye,
  search: IconSearch,
  bell: IconBell,
  chevronDown: IconChevronDown,
  chevronUp: IconChevronUp,
  chevronRight: IconChevronRight,
  chevronLeft: IconChevronLeft,
  dots: IconDots,
  message: IconMessage,
  fileText: IconFileText,
  copy: IconCopy,
  trash: IconTrash,
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  list: IconList,
  listNumber: IconListNumbers,
  link: IconLink,
  image: IconPhoto,
  quote: IconQuote,
  bolt: IconBolt,
  sparkles: IconSparkles,
  folder: IconFolder,
  users: IconUsers,
  arrowRight: IconArrowRight,
  arrowUpRight: IconArrowUpRight,
  refresh: IconRefresh,
  save: IconDeviceFloppy,
  layers: IconStack2,
  target: IconTarget,
  eyeOff: IconEyeOff,
  history: IconHistory,
  filter: IconFilter,
  gripper: IconGripVertical,
  logout: IconLogout,
  alert: IconAlertTriangle,
  inbox: IconInbox,
  hash: IconHash,
  trendingUp: IconTrendingUp,
  download: IconDownload,
  globe: IconWorld,
  comment: IconMessageCircle,
} satisfies Record<string, TablerIcon>;

export type IconName = keyof typeof Icon;
