// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountStatus } from "./AccountStatus";
import type { PlatformId } from "./PlatformId";

/**
 * `camelCase` so field names match the frontend (`loginId`, not `login_id`).
 */
export type Account = { id: string, platform: PlatformId, loginId: string, pw: string, status: AccountStatus, last: string, tags: Array<string>, };
