// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 계정의 로그인/활동 상태. `new`/`active`/`error`는 기존과 동일한 와이어 형태를 유지하고
 * (camelCase에서도 단일 단어라 그대로), 로그인 결과를 세분화하는 세 값을 추가한다:
 * `badCredentials`(아이디/비밀번호 오류), `challenge`(캡차·OTP·기기 등 추가 인증 필요),
 * `blocked`(접근 차단). `error`는 그 외(전송 오류/타임아웃/미상)의 catch-all로 남겨,
 * 디스크에 이미 저장된 `"error"` 값과의 하위호환을 보장한다.
 */
export type AccountStatus = "new" | "active" | "waiting" | "onHold" | "timedOut" | "badCredentials" | "challenge" | "blocked" | "error";
