// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityType } from "./ActivityType";

export type ActivityItem = { id: string, type: ActivityType, text: string, at: number, };
