// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ADB 디바이스 감지 상태.
 */
export type AdbStatus = { 
/**
 * USB 디바이스가 감지되었는지 여부.
 */
connected: boolean, 
/**
 * 미연결/스캔 실패 사유(연결된 경우 None). 미연결은 정상 상태로 취급.
 */
error: string | null, };
