// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Article } from "./Article";

/**
 * 게시글 목록 조회 결과 — UI 반환용.
 */
export type ArticleListResponse = { 
/**
 * 조회된 게시글 목록.
 */
articles: Array<Article>, 
/**
 * 마지막 페이지 여부.
 */
lastPage: boolean, };
