// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UI로 반환하는 게시글 1건 (slim).
 *
 * 원본 응답의 다수 필드 중 목록 표시에 필요한 것만 추린다. 작성자 식별용
 * 민감 필드(`memberKey` 등)는 내부 구조체에 선언하지 않아 자동 배제된다.
 */
export type Article = { 
/**
 * 숫자 게시글 ID. (JS `number` — [`crate::ipc::cafes::Board`] 참고)
 */
articleId: number, 
/**
 * 게시글 제목.
 */
subject: string, 
/**
 * 작성자 닉네임.
 */
writerNickname: string, 
/**
 * 글이 속한 게시판(메뉴) ID.
 */
menuId: number, 
/**
 * 게시판 이름 (예: "자유게시판").
 */
menuName: string, 
/**
 * 댓글 수.
 */
commentCount: number, 
/**
 * 조회 수.
 */
readCount: number, 
/**
 * 좋아요 수.
 */
likeCount: number, 
/**
 * 작성 시각(epoch millis).
 */
writeDateTimestamp: number, };
