// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UI로 반환하는 게시글 1건 (slim).
 *
 * 최신글·인기글 두 응답을 공통 형태로 합친다. 최신글 응답엔 작성자 닉네임이
 * 없어(`writerInfo.memberKey`만 존재) `writer_nickname`이 빈 문자열이고,
 * 인기글 응답엔 게시판 이름이 없어 `menu_name`이 빈 문자열이다.
 */
export type Article = { 
/**
 * 숫자 게시글 ID — 댓글 대상이 되는 값.
 */
articleId: number, 
/**
 * 게시글 제목.
 */
subject: string, 
/**
 * 작성자 닉네임 (최신글 응답엔 없어 빈 문자열).
 */
writerNickname: string, 
/**
 * 글이 속한 게시판(메뉴) ID.
 */
menuId: number, 
/**
 * 게시판 이름 (인기글 응답엔 없어 빈 문자열).
 */
menuName: string, 
/**
 * 댓글 수.
 */
commentCount: number, 
/**
 * 조회 수.
 */
readCount: number, 
/**
 * 좋아요 수 (최신글 `likeCount` / 인기글 `upCount`).
 */
likeCount: number, 
/**
 * 작성 시각(epoch millis).
 */
writeDateTimestamp: number, };
