// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 밴드(band.us) 게시 대상 1건 (`band_post::band_publish`의 재료). `account_id`는 band
 * 로그인 쿠키 키(= loginId) 규약을 따른다. 밴드는 forum처럼 글/댓글 분리 개념이 아니라
 * 항상 글을 쓰고(comment/both면 그 글에 댓글), `kind`와 독립적으로 동작한다.
 */
export type BandTarget = { accountId: string, 
/**
 * 밴드 표시 이름(예약 시점 동결). 완료 로그/큐 표시에 ID 대신 보여준다.
 */
name: string, 
/**
 * band.us 가입·게시 링크(또는 band_no). `band_publish`가 여기서 band_no를 추출한다.
 */
link: string, };
