// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentTargetSpec } from "./CommentTargetSpec";

/**
 * 밴드(band.us) 게시 대상 1건. `account_id`는 band 로그인 쿠키 키(= loginId) 규약을
 * 따른다. post/both 모드는 새 글을 쓰고(both면 그 글에 댓글) `band_publish`로, comment
 * 전용 모드는 기존 글(최신/인기) 상위 N개에 댓글을 다는 `band_comment`로 처리된다.
 */
export type BandTarget = { accountId: string, 
/**
 * 밴드 표시 이름(예약 시점 동결). 완료 로그/큐 표시에 ID 대신 보여준다.
 */
name: string, 
/**
 * band.us 가입·게시 링크(또는 band_no). `band_publish`가 여기서 band_no를 추출한다.
 */
link: string, 
/**
 * 댓글 전용 모드(`kind == Comment`)에서 댓글을 달 기존 글 대상. post/both면 None.
 * 밴드는 url 댓글을 지원하지 않아 `mode`는 latest/popular만 의미가 있다(url이면
 * 호출부가 latest로 폄). `cafe_id`/`article_id`는 밴드에서 쓰지 않는다.
 */
commentTarget?: CommentTargetSpec, };
