// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single-variant enum → ts-rs emits the `"running"` string-literal type the
 * frontend's optional `state?: "running"` field expects.
 */
export type BatchState = "running";
