// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchItemStatus } from "./BatchItemStatus";
import type { PlatformId } from "./PlatformId";

export type BatchItem = { platform: PlatformId, target: string, code?: string, board?: string, loginId: string, status: BatchItemStatus, msg: string, trace?: string, };
