// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 네이버 블로그 댓글 게시 대상 1건(#271). 블로그는 댓글 전용이라 카페와 같은 네이버
 * 저장 쿠키를 재사용한다(별도 로그인 없음). `accountId`는 로그인 쿠키 키(= loginId) 규약을
 * 따른다. `blogId`는 문자열 식별자(예: "press02"), `logNo`는 숫자 글 id 문자열(예:
 * "224311392458"). `name`은 완료 로그/큐 표시용, `link`는 원본 글 URL이다.
 */
export type BlogTarget = {
  accountId: string;
  name: string;
  blogId: string;
  logNo: string;
  link: string;
};
