// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single writable board (menu) inside a cafe, as resolved at registration.
 */
export type Board = { 
/**
 * Display name (e.g. "자유게시판").
 */
name: string, 
/**
 * Numeric board (menu) id — used by the article-write API. Maps to a JS
 * `number` (not `bigint`): IPC serializes via JSON and cafe/menu ids stay
 * well within `Number.MAX_SAFE_INTEGER`.
 */
menuId: number, 
/**
 * Board layout type (e.g. "L") — used in the write Referer header.
 */
boardType: string, };
