// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";

/**
 * A publish-target cafe. Resolved once at registration and cached.
 */
export type Cafe = { 
/**
 * Display name.
 */
name: string, 
/**
 * Original reference the user entered (URL/slug/numeric) — kept for
 * re-resolution and display.
 */
cafeRef: string, 
/**
 * Resolved numeric cafe id. Maps to a JS `number` (see [`Board::menu_id`]).
 */
cafeId: number, 
/**
 * Writable boards discovered at registration.
 */
boards: Array<Board>, };
