// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentPublishOutcome } from "./CommentPublishOutcome";
import type { PublishOutcome } from "./PublishOutcome";

/**
 * Result of one "지금 바로 게시"(immediate publish) run for naver cafe — the slim
 * post and comment outcomes the publish modal renders inline. The alert-log
 * recording is already done backend-side (see `run_cafe_publish_now` in
 * `queue_runner`) from the rich reports, so this carries only what the UI needs.
 */
export type CafePublishNowResult = { 
/**
 * Article-post results (post/both modes). Empty for comment-only runs.
 */
posts: Array<PublishOutcome>, 
/**
 * Comment results (comment/both modes). Empty for post-only runs.
 */
comments: Array<CommentPublishOutcome>, };
