// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chrome 실행 파일 설치/버전 상태.
 */
export type ChromeStatus = { 
/**
 * Chrome 경로를 찾았는지 여부.
 */
installed: boolean, 
/**
 * 찾은 실행 파일 경로(설치된 경우).
 */
path: string | null, 
/**
 * `--version` 으로 읽은 버전(읽기 실패 시 None = "버전 미상").
 */
version: string | null, 
/**
 * 미설치/경로 오류 사유(설치된 경우 None).
 */
error: string | null, };
