// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 네이버 클립 댓글 게시 대상 1건(#클립). 블로그처럼 네이버 저장 쿠키를 재사용하는 댓글 전용
 * 대상이며, 댓글 전 클립 프로필 생성을 워커가 보장한다. `accountId`는 로그인 쿠키 키(= loginId),
 * `handle`은 창작자 핸들(@ 제외, 예: "dongzzi_chef"), `count`는 최신 N개, `mediaType`은
 * "video"면 영상만/그 외 전체. `name`은 표시용, `link`는 원본 링크다.
 */
export type ClipTarget = {
  accountId: string;
  name: string;
  handle: string;
  link: string;
  count?: number;
  mediaType?: string;
};
