// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One comment destination — the account plus the numeric cafe/article it will
 * comment on. The comment *text* is not chosen here: the backend deals it from
 * the pool (see [`run_comment_jobs`]). Comes either from a just-posted article
 * or a URL the UI parsed.
 */
export type CommentDistributionTarget = { 
/**
 * Account the comment runs under (cookie-file lookup key).
 */
accountId: string, 
/**
 * Target cafe id. (JS `number`)
 */
cafeId: number, 
/**
 * Target article id the comment attaches to.
 */
articleId: number, };
