// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 댓글 작성 작업 1건 — `(계정, 카페, 게시글, 내용)` 조합.
 *
 * [`PostJob`]과 달리 카페/게시글을 **숫자 ID로 이미 확정한 상태**로 받는다.
 * (글 작성 직후의 `articleId` 재사용, 또는 URL 파싱 결과를 UI가 채운다.)
 * 이 단계(척추)는 카페 해석·글목록 조회를 일절 하지 않는다.
 */
export type CommentJob = { 
/**
 * 사용할 계정 ID (쿠키 파일 조회 키).
 */
accountId: string, 
/**
 * 대상 카페의 숫자 ID. (JS `number` — [`PostJob::menu_id`] 참고)
 */
cafeId: number, 
/**
 * 댓글을 달 대상 게시글의 숫자 ID.
 */
articleId: number, 
/**
 * 댓글 본문.
 */
content: string, };
