// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentTarget } from "./CommentTarget";

/**
 * 댓글 게시 대상 지정. `mode`가 `latest`/`popular`면 `count`(상위 N개)를, `url`이면
 * `cafe_id`/`article_id`를 사용한다. 표시용 enum `CommentTarget`을 재사용한다.
 */
export type CommentTargetSpec = { mode: CommentTarget, count?: number, cafeId?: number, articleId?: number, };
