// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slim per-job comment result returned to the UI. The rich internal
 * `CommentJobReport`/`CommentError` stays backend-only — mirrors
 * [`PublishOutcome`] for the post path.
 */
export type CommentPublishOutcome = { 
/**
 * Account the job ran under.
 */
accountId: string, 
/**
 * Target cafe id.
 */
cafeId: number, 
/**
 * Target article id the comment was posted to.
 */
articleId: number, 
/**
 * Whether the comment was posted.
 */
success: boolean, 
/**
 * Registered comment id, on success.
 */
commentId?: number, 
/**
 * Error code, on failure (e.g. "NO_COOKIES", "COMMENT_HTTP_ERROR").
 */
errorCode?: string, 
/**
 * Human-readable error message, on failure. Never contains cookie values.
 */
errorMessage?: string, };
