// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentDistributionTarget } from "./CommentDistributionTarget";

/**
 * Request for [`run_comment_jobs`]: the destinations plus the comment pool.
 * The backend shuffles `comments` and deals one to each target (issue #98), so
 * different accounts post different comments — matching the UI's promise.
 */
export type CommentDistributionRequest = { 
/**
 * Where each comment lands (one comment dealt per target).
 */
targets: Array<CommentDistributionTarget>, 
/**
 * The comment text pool to distribute across the targets.
 */
comments: Array<string>, };
