// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 글 내용 변경(설계서 §5). 글쓰기 게시일 때만 채워진다: 원본으로 글을 게시하고 delaySec초
 * 뒤 여기 담긴 새 제목/본문으로 edit(PUT edit)한다.
 */
export type ContentChange = { title: string, body: string, delaySec: number, };
