// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatValue } from "./StatValue";

export type DashStat = { key: string, label: string, value: StatValue, sub: string, icon: string, color: string, };
