// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdbStatus } from "./AdbStatus";
import type { ChromeStatus } from "./ChromeStatus";

/**
 * Chrome + ADB 진단을 한 번에 묶은 결과.
 */
export type EnvironmentStatus = { chrome: ChromeStatus, adb: AdbStatus, };
