// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForumStock } from "./ForumStock";

/**
 * 한 페이지 결과 + 페이지네이션 메타.
 */
export type ForumStockPage = { stocks: Array<ForumStock>, totalCount: number, page: number, hasNext: boolean, };
