// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 종목토론방 게시 대상 1건 (`ForumPublishRequest`의 stock 재료).
 */
export type ForumTarget = { accountId: string, name: string, code: string, };
