// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 종목 선택 화면 상단 카테고리 6종. 프론트는 camelCase 문자열로 전달한다.
 */
export type ForumStockCategory = "discussion" | "tradingValue" | "popular" | "rising" | "falling" | "volume";
