// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 종목 한 줄(선택 가능한 종목). 프론트가 그대로 렌더한다.
 */
export type ForumStock = { code: string, name: string, 
/**
 * KOSPI / KOSDAQ (표시용). 알 수 없으면 빈 문자열.
 */
exchange: string, 
/**
 * 현재가(포맷된 문자열). 검색 결과처럼 가격이 없으면 빈 문자열.
 */
price: string, 
/**
 * 등락률(예 "-7.68"). 없으면 빈 문자열.
 */
changeRate: string, 
/**
 * "rising" | "falling" | "even" (색상용). 없으면 "even".
 */
changeType: string, 
/**
 * 지금 토론 활발 종목이면 true(🔥).
 */
isHotDiscussion: boolean, };
