// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 엑셀 가져오기 결과 요약.
 */
export type ImportSummary = { imported: number, skipped: number, errors: Array<string>, };
