// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UI로 반환하는 가입 카페 1건 (slim).
 *
 * 원본 응답의 다수 필드 중 게시 대상 선택에 필요한 것만 추린다.
 * `cafe_url`은 전체 URL이 아니라 **슬러그**다(`cafe.naver.com/<cafe_url>`).
 */
export type JoinedCafe = { 
/**
 * 숫자 카페 ID. (JS `number` — [`crate::ipc::cafes::Board`] 참고)
 */
cafeId: number, 
/**
 * 카페 표시 이름.
 */
cafeName: string, 
/**
 * 카페 슬러그 (`cafe.naver.com/<cafe_url>`).
 */
cafeUrl: string, 
/**
 * 이 계정의 카페 내 닉네임.
 */
memberNickname: string, 
/**
 * 이 계정의 등급명 (예: "카페매니저", "성실회원") — 글쓰기 권한 신호.
 */
memberLevelname: string, 
/**
 * 내가 관리(매니저)하는 카페인지 여부.
 */
managingCafe: boolean, 
/**
 * 휴면 카페 여부(글쓰기 제약 신호).
 */
dormantCafe: boolean, };
