// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentTarget } from "./CommentTarget";
import type { ModeValue } from "./ModeValue";
import type { PostStatus } from "./PostStatus";

export type LibraryPost = { id: string, title: string, kind: ModeValue, updated: string, words: number, status: PostStatus, excerpt: string, body?: string, comments?: Array<string>, commentTarget?: CommentTarget, commentUrl?: string, commentCount?: number, };
