// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchItem } from "./BatchItem";
import type { BatchState } from "./BatchState";
import type { ModeValue } from "./ModeValue";

export type LogBatch = { id: string, title: string, kind: ModeValue, time: string, state?: BatchState, items: Array<BatchItem>, };
