// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformId } from "./PlatformId";

/**
 * 로그인 배치의 계정 1건. `account_id`는 로그인 쿠키 키(= loginId) 규약을 따른다.
 * `platform`이 `Band`면 band.us 로그인(`process_band_account`), 그 외(naver/forum 등)는
 * 네이버 로그인(`process_account`)으로 처리된다(프론트 `runLogin`의 naver/band 분기 미러).
 */
export type LoginTarget = { accountId: string, platform: PlatformId, headless: boolean, useAdb: boolean, force: boolean, };
