// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentTargetSpec } from "./CommentTargetSpec";

/**
 * 네이버 카페 게시 대상 1건 (orchestrator `PostJob`의 재료). `account_id`는 로그인 쿠키
 * 키(= loginId) 규약을 따른다.
 */
export type NaverTarget = { accountId: string, cafe: string, menuId: number, boardType: string, 
/**
 * comment/both 모드에서 댓글을 달 대상. post 전용이면 None.
 */
commentTarget?: CommentTargetSpec, };
