// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors the TS `PlatformId` literal union. `lowercase` keeps the JSON wire
 * form identical to the existing frontend values (`"forum"`, `"naver"`, …).
 */
export type PlatformId = "forum" | "naver" | "band" | "instagram" | "threads";
