// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 한 대상에 실제로 게시된 내용(종목별 토큰 치환 후). 글이 빛삭돼도 무엇을 보냈는지
 * 완료 로그에서 확인할 수 있게 종목별로 보존한다.
 */
export type PostedContent = { title: string, body: string, comment?: string, url?: string, };
