// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 글 작성 작업 1건 — `(계정, 카페, 게시판, 내용)` 조합.
 */
export type PostJob = { 
/**
 * 사용할 계정 ID (쿠키 파일 조회 키).
 */
accountId: string, 
/**
 * 대상 카페 — URL, vanity 슬러그, 또는 숫자 cafeId 문자열 모두 허용.
 */
cafe: string, 
/**
 * 선택된 게시판(메뉴) ID. (JS `number` — [`crate::ipc::cafes::Board`] 참고)
 */
menuId: number, 
/**
 * 선택된 게시판의 `boardType` (예: `"L"`) — 글쓰기 Referer 헤더에 사용.
 */
boardType: string, 
/**
 * 게시글 제목.
 */
subject: string, 
/**
 * 게시글 본문 텍스트.
 */
bodyText: string, 
/**
 * 태그 목록.
 */
tagList: Array<string>, };
