// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slim per-job result returned to the UI — exactly what the publish modal
 * renders. The rich internal `JobReport`/`PostError` stays backend-only.
 */
export type PublishOutcome = { 
/**
 * Account the job ran under.
 */
accountId: string, 
/**
 * Original cafe reference the job targeted.
 */
cafe: string, 
/**
 * Target board (menu) id.
 */
menuId: number, 
/**
 * Whether the article was posted.
 */
success: boolean, 
/**
 * Registered article id, on success.
 */
articleId?: number, 
/**
 * Error code, on failure (e.g. "INVALID_CAFE_INPUT", "NO_COOKIES").
 */
errorCode?: string, 
/**
 * Human-readable error message, on failure. Never contains cookie values.
 */
errorMessage?: string, };
