// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForumTarget } from "./ForumTarget";
import type { ModeValue } from "./ModeValue";
import type { NaverTarget } from "./NaverTarget";

/**
 * 큐 아이템을 실제로 게시하는 데 필요한 동결된 실행 페이로드.
 */
export type PublishPlan = { 
/**
 * 출처 글(LibraryPost) id — 추적/표시용. 본문은 아래 필드에 동결되어 있다.
 */
postId: string, kind: ModeValue, title: string, bodyText: string, comments: Array<string>, naver: Array<NaverTarget>, forum: Array<ForumTarget>, };
