// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BandTarget } from "./BandTarget";
import type { BlogTarget } from "./BlogTarget";
import type { ClipTarget } from "./ClipTarget";
import type { ForumTarget } from "./ForumTarget";
import type { LoginTarget } from "./LoginTarget";
import type { ModeValue } from "./ModeValue";
import type { NaverTarget } from "./NaverTarget";

/**
 * 큐 아이템을 실제로 게시하는 데 필요한 동결된 실행 페이로드.
 */
export type PublishPlan = {
/**
 * 출처 글(LibraryPost) id — 추적/표시용. 본문은 아래 필드에 동결되어 있다.
 */
postId: string, kind: ModeValue, title: string, bodyText: string, comments: Array<string>,
/**
 * `#{링크}` 토큰 치환에 쓸 사용자 지정 링크값(선택). 비우면 종목별 시세 링크를 쓴다.
 */
linkOverride: string, naver: Array<NaverTarget>, forum: Array<ForumTarget>, band: Array<BandTarget>, blog: Array<BlogTarget>, clip: Array<ClipTarget>,
/**
 * 로그인 전용 아이템의 계정 목록. 게시 아이템에는 없다(직렬화 생략 → 기존 plan과 호환).
 * 워커(`execute_item`)는 이 필드가 채워진 아이템을 게시 대신 계정별 로그인으로 처리한다
 * (배치 1개 = 아이템 1개, 진행률 분모 = 계정 수). 일원화: 로그인도 now 큐로 흐른다(#210).
 */
login?: Array<LoginTarget>, };
