// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeValue } from "./ModeValue";
import type { QueueLocation } from "./QueueLocation";

export type QueueScheduledItem = { id: string, title: string, kind: ModeValue, when: string, rel: string, locs: Array<QueueLocation>, };
