// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeValue } from "./ModeValue";
import type { QueueLocation } from "./QueueLocation";
import type { QueueState } from "./QueueState";

export type QueueNowItem = { id: string, title: string, kind: ModeValue, state: QueueState, batchId?: string, progress?: [number, number], locs: Array<QueueLocation>, };
