// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeValue } from "./ModeValue";
import type { PublishPlan } from "./PublishPlan";
import type { QueueLocation } from "./QueueLocation";
import type { QueueState } from "./QueueState";

export type QueueNowItem = { id: string, title: string, kind: ModeValue, state: QueueState, batchId?: string, progress?: [number, number], locs: Array<QueueLocation>, 
/**
 * 워커가 실제 게시에 사용하는 실행 페이로드. 레거시/표시 전용 아이템은 None.
 */
plan?: PublishPlan, };
