// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchItem } from "./BatchItem";
import type { ModeValue } from "./ModeValue";
import type { PublishPlan } from "./PublishPlan";
import type { QueueLocation } from "./QueueLocation";
import type { QueueState } from "./QueueState";

export type QueueNowItem = { id: string, title: string, kind: ModeValue, state: QueueState, batchId?: string, progress?: [number, number], locs: Array<QueueLocation>, 
/**
 * 워커가 실제 게시에 사용하는 실행 페이로드. 레거시/표시 전용 아이템은 None.
 */
plan?: PublishPlan, 
/**
 * 워커가 phase별로 갱신하는 대상별 실시간 상태(진행 전/중/완료/실패). 알림 로그와
 * 같은 `BatchItem` 모델을 재사용해 프론트가 SubLog를 그대로 쓴다. 대기/표시 전용
 * 아이템은 빈 Vec(레거시 JSON엔 키가 없어 기본값 빈 Vec로 역직렬화).
 */
items: Array<BatchItem>, };
