// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeValue } from "./ModeValue";

export type Scheduled = { id: string, title: string, accounts: Array<string>, kind: ModeValue, when: string, rel: string, };
