// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 게시글 목록 정렬 기준 — 최신글 / 인기글.
 *
 * API 쿼리 파라미터 `sortBy`로 매핑된다(최신글=`TIME`, 인기글=`LIKE`).
 */
export type SortBy = "latest" | "popular";
