// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 거래소(KRX/NXT). 프론트는 "krx"/"nxt"로 전달한다.
 */
export type StockExchange = "krx" | "nxt";
