// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Stock = { code: string, name: string, market: string, posts: string, price: string, chg: number, };
