// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 시장 구분(전체/코스피/코스닥). 프론트는 "all"/"kospi"/"kosdaq"로 전달한다.
 * 토론(Discussion)은 네이버가 시장 분리를 제공하지 않으므로 이 값을 무시한다.
 */
export type StockMarket = "all" | "kospi" | "kosdaq";
